### PR TITLE
chg: [screen] Added a width parameter

### PR DESCRIPTION
**Pull request by SteveClement**

### CODE REVIEW

**Comment by lordmauve** [comment]
The `filled_` versions must not accept `width`, as that makes them not filled.

The reason `width` was not exposed was due to bugs in Pygame that caused them to draw with moiré patterns. I believe this is fixed in recent Pygame.

Also, please can you add a test for this?

**Comment by lordmauve** [comment]
This looks good. Please can you document the extra parameters in https://github.com/lordmauve/pgzero/blob/master/doc/builtins.rst ?

Also, could you rebase your branch? It isn't in a mergeable state.

**Comment by SteveClement** [comment]
Ok, I will add the missing tests and use test_polygon as a guideline.

**Comment by SteveClement** [comment]
ok, this should be more or less it @lordmauve 

I also fixed Travis, a little sloppily by adding #noqa not sure how you want to handle that.

**Comment by lordmauve** [comment]
I haven't finished getting Travis working for Pygame Zero at this point, so I'm happy with whatever.

This is still saying "This branch cannot be rebased due to conflicts". Please can you rebase from master (eg. `git pull --rebase upstream master`) and if successful, force-push the result?

**Comment by SteveClement** [comment]
@lordmauve I rebased and re-did the changes. My UI tells me: "This branch has no conflicts with the base branch"

**Comment by lordmauve** [comment]
Thank you!

**Pull request merged**
